### ISSUE TITLE
A few issues while using the app

### ISSUE THREAD

**Issue by MikePerreman** [Marxlp/pyFlightAnalysis#13]
Ok, there's a few.

so, loading data into the app, and hitting play causes this to happen:
```
C:\Users\mikep\Desktop> analysis
C:\Python\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\pyflightanalysis-1.0.4b1-py3.6.egg\pyflightanalysis\analysis.py", line 358, in animation_update
    state_data = [self.position_history[indexes[0]],
TypeError: 'map' object is not subscriptable
```

Trying to export the graph:
```
C:\Users\mikep\Desktop> analysis
C:\Python\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "C:\Python\Anaconda3\lib\site-packages\pyqtgraph\exporters\ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer
```

trying to run the simulation: 
```
C:\Users\mikep\Desktop> analysis
C:\Python\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\pyflightanalysis-1.0.4b1-py3.6.egg\pyflightanalysis\analysis.py", line 381, in callback_show_quadrotor
    splash = ThreadQDialog(self.quadrotor_win.quadrotor_widget,self.quadrotor_win)
  File "C:\Python\Anaconda3\lib\site-packages\pyflightanalysis-1.0.4b1-py3.6.egg\pyflightanalysis\analysis.py", line 661, in __init__
    self.connect(self.loading_widget,QtCore.SIGNAL('loadFinished(bool)'),self.callback_close)
AttributeError: 'ThreadQDialog' object has no attribute 'connect'
```

There are more, I think I may have installed wrong. I dont have these issues in other programs, though.

**Comment by superbraw** [comment]
Please, let me know if you resolve this issue. I been trying to start the simulation but quits on me just like you.
Let me know if you end up fixing this issue. Please

**Comment by Marxlp** [comment]
This is due to the different version of python. You could try python2.x first. And I am debugging the code. If I finished, I will tell you here.

**Comment by Marxlp** [comment]
@MikePerreman @superbraw 
- issue 1
 python3.x map function return an iterator not a list.
- issue 2
 It's a bug in pyqtgraph (check [https://github.com/pyqtgraph/pyqtgraph/issues/722](https://github.com/pyqtgraph/pyqtgraph/issues/722)), you can fix it temporarily by changing line 70 in the file ```C:\Python\Anaconda3\lib\site-packages\pyqtgraph\exporters\ImageExporter.py``` like this
```python
bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)
```
- issue 3
 It's due to the PyQt5 didn't implement the SIGNAL function in PyQt4.

I have update the code. You can install newest package and solve the issue 2 like above to fix these issues.
