### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by mengchaoheng** [Marxlp/pyFlightAnalysis#19]
after analysis:
Traceback (most recent call last):
  File "/home/mch/.local/bin/analysis", line 7, in <module>
    from pyflightanalysis.analysis import main
  File "/home/mch/.local/lib/python2.7/site-packages/pyflightanalysis/analysis.py", line 20, in <module>
    from widgets import QuadrotorWin, InfoWin, TabWidget
  File "/home/mch/.local/lib/python2.7/site-packages/pyflightanalysis/widgets.py", line 161, in <module>
    class QuadrotorWidget(QtOpenGL.QGLWidget):
  File "/home/mch/.local/lib/python2.7/site-packages/pyqtgraph/Qt.py", line 56, in __getattr__
    raise self.err
ImportError: cannot import name QtOpenGL

**Comment by Marxlp** [comment]
I notice that you are using Python2.7. As described in the [README](https://github.com/Marxlp/pyFlightAnalysis), you should use Python3.x.
