### ISSUE TITLE
Installation from pip fails - no module widgets

### ISSUE THREAD

**Issue by hamishwillee** [Marxlp/pyFlightAnalysis#4]
I have a python3 virtual environment in which I first installed PyQt5  and then pyFlightAnalysis - see env below:
```
(mypy3env) ubuntu@ubuntu:~/github/pyFlightAnalysis$ pip list
numpy (1.14.3)
pip (8.1.1)
pkg-resources (0.0.0)
pyFlightAnalysis (1.0.1b1)
PyOpenGL (3.1.0)
PyQt5 (5.10.1)
pyqtgraph (0.10.0)
pyulog (0.6.0)
setuptools (20.7.0)
sip (4.19.8)
```
When I try run `analysis` I get error:
```
ubuntu@ubuntu:~/github/pyFlightAnalysis$ analysis
Traceback (most recent call last):
  File "/home/ubuntu/github/pyFlightAnalysis/mypy3env/bin/analysis", line 7, in <module>
    from pyflightanalysis.analysis import main
  File "/home/ubuntu/github/pyFlightAnalysis/mypy3env/lib/python3.5/site-packages/pyflightanalysis/analysis.py", line 16, in <module>
    from widgets import QuadrotorWin
ImportError: No module named 'widgets'
```

Similarly, building from source fails - as you would expect because dependency is missing. See #5

**Comment by Marxlp** [comment]
run command in your virtual environment
```bash
> ls mypy3env/lib/python3.5/site-packages/pyflightanalysis/
```
check whether  `widgets.py`  exists along with `analysis.py`

**Comment by hamishwillee** [comment]
Yes it is present:
```
(mypy3env) ubuntu@ubuntu:~/github/pyFlightAnalysis$ ls mypy3env/lib/python3.5/site-packages/pyflightanalysis/
analysis.py  icons  __init__.py  models  objloader.py  __pycache__  widgets.py
(mypy3env) ubuntu@ubuntu:~/github/pyFlightAnalysis$ 
```

**Comment by Marxlp** [comment]
I fixed the problem. It's due the module name will change when run a module as a file. Details see [here](https://stackoverflow.com/questions/11536764/how-to-fix-attempted-relative-import-in-non-package-even-with-init-py).
Reinstalling it from pypi will fix this issue.
